### DISCUSSION TITLE
Device Time Out / Netmiko Options

### DISCUSSION THREAD

**Discussion by jvanderaa** [networktocode/network-importer#248] [Q&A]
Should one need to increase the timeout, or set any of the Netmiko timeouts that would be involved, the following configuration options can be added to the configuration:

```toml
[network.netmiko_extras]
global_delay_factor=5
banner_timeout=40
conn_timeout=30
```
