### ISSUE TITLE
Provide valid examples of the `network_importer.toml` configuration file

### ISSUE THREAD

**Issue by dteycheney** [networktocode/network-importer#230]
### Environment
* Python version:  3.8.10
* Network Importer version:  

### Proposed Functionality

It would be good to provide a couple of examples for both netbox and nautobot of some working examples
of the [network-importer configuration file](
https://github.com/networktocode/network-importer/blob/develop/network_importer.toml)
that are compatible with version 3 or higher.

There are some [examples](https://github.com/networktocode/network-importer/tree/develop/examples) but it's unclear which version of network-importer they are for.

**Comment by dteycheney** [comment]
FYI @tim-fiola

**Comment by jvanderaa** [comment]
@dteycheney does this page cover it? https://github.com/networktocode/network-importer/blob/develop/docs/getting_started.md

There are a couple of examples throughout.

**Comment by jvanderaa** [comment]
That is the one that I have used very successfully and have documented in other places with the demo.

**Comment by dteycheney** [comment]
@jvanderaa, maybe I wasn't too clear so I'll explain a little further.

There is a [network-importer](https://github.com/networktocode/network-importer/blob/develop/network_importer.toml) file at the base of the project, which I tried to use initially.

Below is the example I got to work with version 3.

```toml
[main]
# Import IP addresses
import_ips = true
# Import prefixes
import_prefixes = true
# Do not import cabling
import_cabling = false
# Import VLANs
import_vlans = true
# Use nautobot as the backend
backend = "nautobot"

[logs]
# Set logging to info
level = "info"

[inventory.settings]
# Setup nautobot server
address = "https://<nautobot_server>"
filter = "platform=panos,platform=ios,platform=iosxe,platform=nxos"

[batfish]
address = "x.x.x.x"   # Alternative Env Variable : BATFISH_ADDRESS
network_name = "<your-network>"
snapshot_name = "<your-snapshot>"
port_v1 = 9997
port_v2 = 9996
use_ssl = false

# Connection parameters for Netmiko
[network.netmiko_extras]
global_delay_factor = 5
banner_timeout = 15
conn_timeout = 5
```

An idea could be structuing the examples. Something like:

```
examples/
    v2/
        nautobot/
           example_one.toml
           example_two.toml
        netbox/
           example_one.toml
           example_two.toml
  v3/
        nautobot/
           example_one.toml
           example_two.toml
        netbox/
           example_one.toml
           example_two.toml
```

Then it's really clear which examples work on what environments.
