### ISSUE TITLE
ER: support NetBox device status assignment based on outcome

### ISSUE THREAD

**Issue by jeremyschulman** [networktocode/network-importer#7]
When the network-importer (NI) tool processes a given device there are three general outcomes that could be used to assign the device state in NetBox:

1. import process was successful
1. import process failed to connect to device, therefore cannot import
1. import process failed during the processing of the device

This ER proposes a change to the NI configuration file so that the User can identify the device status value (slug) that NI will assign upon those outcomes.  The following is an example.

_Note: the variable names (when_device_unreachable) are provided for example purposes only and could be different in the eventual implementation._

````toml
[netbox]
when_import_unreachable = "Offline"
when_import_fail = "Failed"
when_import_pass = "Active"
````
If any of these when variables are not provided, then the NI process will *not* modify the device status value; event when the import completes without error.
